server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      force: true

spring:
  batch:
    jdbc:
      initialize-schema: always

    job:
      enabled: true

  data:
    redis:
      port: ${spring.data.redis.port}
      host: ${spring.data.redis.host}
      repositories:
        enabled: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${mysql.url}/${database.name}
    username: ${mysql.username}
    password: ${mysql.password}

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
        use_sql_comments: true
        auto_quote_keyword: true

    hibernate:
      ddl-auto: update

  sql:
    init:
      mode: always
      schema-locations: classpath:schema-mysql.sql

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
    tags-sorter: alpha

admin:
  key: ${admin.key}
  prefix: ${admin.prefix}

jwt:
  secret:
    key: ${jwt.secret.key}
